# Generated by Django 5.0.1 on 2024-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('make', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(default='media/ElektrJihozlar/default_laptop', upload_to='media/ElektrJihozlar')),
            ],
        ),
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('make', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('SD', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='media/ElektrJihozlar/default_elektr_jihozlari.', upload_to='media/ElektrJihozlar')),
            ],
        ),
    ]
