# Generated by Django 5.0.1 on 2024-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BolalarKiyimlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(default='media/BolalarDunyosi/default_bolalar_kiyimlari.', upload_to='media/BolalarDunyosi')),
            ],
        ),
        migrations.CreateModel(
            name='BolalarOyinchoqlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(default='media/BolalarDunyosi/default_bolalar_oyinchoqlari.', upload_to='media/BolalarDunyosi')),
            ],
        ),
    ]
