# Generated by Django 5.0.1 on 2024-01-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('image', models.ImageField(default='media/Hayvonlar/default_it.', upload_to='media/Hayvonlar')),
                ('price', models.PositiveIntegerField()),
                ('race', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mushuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('race', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='media/Hayvonlar/default_mushuk', upload_to='media/Hayvonlar')),
            ],
        ),
    ]
